/*
 * Juspay Router - API Documentation
 *
 * ## Get started Juspay Router provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes</a>. You can consume the APIs directly using your favorite HTTP/REST library. We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. ### Base URLs Use the following base URLs when making requests to the APIs:    | Environment   |      Base URL                                        |   |---------------|------------------------------------------------------|   | Sandbox       | <https://sandbox.hyperswitch.io>                   |   | Production    | <https://router.juspay.io>                           |  # Authentication When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key). You may authenticate all API requests with Juspay server by providing the appropriate key in the request Authorization header. Never share your secret api keys. Keep them guarded and secure. 
 *
 * API version: 0.2
 * Contact: support@juspay.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PaymentMethodsEnabledInner struct {
	PaymentMethod *PaymentMethod `json:"payment_method,omitempty"`
	PaymentMethodTypes []PaymentMethodType `json:"payment_method_types,omitempty"`
	// List of payment method issuers to be enabled for this payment method
	PaymentMethodIssuers []string `json:"payment_method_issuers,omitempty"`
	// List of payment schemes accepted or has the processing capabilities of the processor
	PaymentSchemes []PaymentSchemes `json:"payment_schemes,omitempty"`
	// List of currencies accepted or has the processing capabilities of the processor
	AcceptedCurrencies []string `json:"accepted_currencies,omitempty"`
	// List of Countries accepted or has the processing capabilities of the processor
	AcceptedCountries []string `json:"accepted_countries,omitempty"`
	// Minimum amount supported by the processor. To be represented in the lowest denomination of the target currency (For example, for USD it should be in cents)
	MinimumAmount int32 `json:"minimum_amount,omitempty"`
	// Maximum amount supported by the processor. To be represented in the lowest denomination of the target currency (For example, for USD it should be in cents)
	MaximumAmount int32 `json:"maximum_amount,omitempty"`
	// Boolean to enable recurring payments / mandates. Default is true.
	RecurringEnabled bool `json:"recurring_enabled,omitempty"`
	// Boolean to enable installment / EMI / BNPL payments. Default is true.
	InstallmentPaymentEnabled bool `json:"installment_payment_enabled,omitempty"`
	// Type of payment experience enabled with the connector
	PaymentExperience []NextAction `json:"payment_experience,omitempty"`
}
