/*
 * Juspay Router - API Documentation
 *
 * ## Get started Juspay Router provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes</a>. You can consume the APIs directly using your favorite HTTP/REST library. We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. ### Base URLs Use the following base URLs when making requests to the APIs:    | Environment   |      Base URL                                        |   |---------------|------------------------------------------------------|   | Sandbox       | <https://sandbox.hyperswitch.io>                   |   | Production    | <https://router.juspay.io>                           |  # Authentication When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key). You may authenticate all API requests with Juspay server by providing the appropriate key in the request Authorization header. Never share your secret api keys. Keep them guarded and secure. 
 *
 * API version: 0.2
 * Contact: support@juspay.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Mandate Payment Create Response
type MandateListResponse struct {
	// The unique id corresponding to the mandate. 
	MandateId string `json:"mandate_id"`
	// The status of the mandate, which indicates whether it can be used to initiate a payment.
	Status string `json:"status"`
	// The type of the mandate. (i) single_use refers to one-time mandates and (ii) multi-user refers to multiple payments.
	Type_ string `json:"type,omitempty"`
	// The id corresponding to the payment method.
	PaymentMethodId string `json:"payment_method_id"`
	// The type of payment method use for the payment. 
	PaymentMethod string `json:"payment_method,omitempty"`
	Card *CardPaymentMethodResponse `json:"card,omitempty"`
	CustomerAcceptance *CustomerAcceptance `json:"customer_acceptance,omitempty"`
}
