/*
 * Juspay Router - API Documentation
 *
 * ## Get started Juspay Router provides a collection of APIs that enable you to process and manage payments. Our APIs accept and return JSON in the HTTP body, and return standard HTTP response codes</a>. You can consume the APIs directly using your favorite HTTP/REST library. We have a testing environment referred to \"sandbox\", which you can setup to test API calls without affecting production data. ### Base URLs Use the following base URLs when making requests to the APIs:    | Environment   |      Base URL                                        |   |---------------|------------------------------------------------------|   | Sandbox       | <https://sandbox.hyperswitch.io>                   |   | Production    | <https://router.juspay.io>                           |  # Authentication When you sign up on our [dashboard](https://app.hyperswitch.io) and create a merchant account, you are given a secret key (also referred as api-key). You may authenticate all API requests with Juspay server by providing the appropriate key in the request Authorization header. Never share your secret api keys. Keep them guarded and secure. 
 *
 * API version: 0.2
 * Contact: support@juspay.in
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WebhookDetails struct {
	// The version for Webhook
	WebhookVersion string `json:"webhook_version,omitempty"`
	// The user name for Webhook login
	WebhookUsername string `json:"webhook_username,omitempty"`
	// The password for Webhook login
	WebhookPassword string `json:"webhook_password,omitempty"`
	// If this property is true, a webhook message is posted whenever a new payment is created
	PaymentCreatedEnabled bool `json:"payment_created_enabled,omitempty"`
	// If this property is true, a webhook message is posted whenever a payment is successful
	PaymentSucceededEnabled bool `json:"payment_succeeded_enabled,omitempty"`
	// If this property is true, a webhook message is posted whenever a payment fails
	PaymentFailedEnabled bool `json:"payment_failed_enabled,omitempty"`
}
